package com.shanghai.templateapp.models.db.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.shanghai.templateapp.models.db.entity.CollectDbEntity;

import com.shanghai.templateapp.models.db.greendao.CollectDbEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig collectDbEntityDaoConfig;

    private final CollectDbEntityDao collectDbEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        collectDbEntityDaoConfig = daoConfigMap.get(CollectDbEntityDao.class).clone();
        collectDbEntityDaoConfig.initIdentityScope(type);

        collectDbEntityDao = new CollectDbEntityDao(collectDbEntityDaoConfig, this);

        registerDao(CollectDbEntity.class, collectDbEntityDao);
    }
    
    public void clear() {
        collectDbEntityDaoConfig.clearIdentityScope();
    }

    public CollectDbEntityDao getCollectDbEntityDao() {
        return collectDbEntityDao;
    }

}
